---
  apiVersion: helm.integrations.flux.weave.works/v1alpha
  kind: FluxHelmRelease
  metadata:
    name: mongodb
    namespace: default
    labels:
      chart: mongodb
  spec:
    chartGitPath: mongodb
    releaseName: mongodb-database4
    testA:
      foo: bar4
    testB:
      foo: bar
    testC:
      foo: bar
    testD:
      foo: bar
    values:
      image: bitnami/mongodb:3.7.1-r1
      imagePullPolicy: IfNotPresent
      persistence.enabled: false
